FROM node:6-alpine as builder

ENV USERNAME node
ENV GROUPNAME node
ENV APP_DIR /srv/app
ENV PATH ${PATH}:${APP_DIR}/node_modules/.bin

WORKDIR ${APP_DIR}

COPY .jshintrc .
COPY .bowerrc .
COPY bower.json .
COPY Gruntfile.js .
COPY package.json .
COPY app app/

RUN set -x \
    && apk add --no-cache \
        wget \
        curl \
        git \
        g++ \
        make \
        python \
        zlib-dev \
    && find ${APP_DIR} -print0 | xargs -0 chown ${USERNAME}:${GROUPNAME}

USER ${USERNAME}

RUN yarn install --pure-lockfile
RUN grunt build

FROM nginx:stable-alpine

ENV APP_DIR /srv/app

WORKDIR ${APP_DIR}

COPY --from=builder ${APP_DIR}/dist .
COPY nginx-site.conf /etc/nginx/conf.d/default.conf
COPY start-nginx.sh /start-nginx.sh

CMD ["sh", "/start-nginx.sh"]
