#!/usr/bin/env sh

PORT=${PORT:-8080}
DOCKER_REGISTRY_SCHEME="http"
ENV_MODE_BROWSE_ONLY=${ENV_MODE_BROWSE_ONLY:-false}
ENV_DOCKER_REGISTRY_HOST=${ENV_DOCKER_REGISTRY_HOST:-127.0.0.1}
ENV_DOCKER_REGISTRY_PORT=${ENV_DOCKER_REGISTRY_PORT:-5000}
ENV_REGISTRY_PROXY_FQDN=${ENV_REGISTRY_PROXY_FQDN:-${ENV_DOCKER_REGISTRY_HOST}}
ENV_REGISTRY_PROXY_PORT=${ENV_REGISTRY_PROXY_PORT:-${ENV_DOCKER_REGISTRY_PORT}}
ENV_DEFAULT_REPOSITORIES_PER_PAGE=${ENV_DEFAULT_REPOSITORIES_PER_PAGE:-20}
ENV_DEFAULT_TAGS_PER_PAGE=${ENV_DEFAULT_TAGS_PER_PAGE:-10}

if [ -n "${ENV_DOCKER_REGISTRY_USE_SSL}" ]; then DOCKER_REGISTRY_SCHEME="https"; fi

# docker-registry-frontend acts as a proxy so may well
# have a different hostname than the registry itself.
echo "{\"host\": \"$ENV_REGISTRY_PROXY_FQDN\", \"port\": $ENV_REGISTRY_PROXY_PORT}" > ${APP_DIR}/registry-host.json
echo "{\"browseOnly\":$ENV_MODE_BROWSE_ONLY, \"defaultRepositoriesPerPage\":$ENV_DEFAULT_REPOSITORIES_PER_PAGE , \"defaultTagsPerPage\":$ENV_DEFAULT_TAGS_PER_PAGE }"  > ${APP_DIR}/app-mode.json

sed -i "s/%PORT%/${PORT}/g; \
        s/%DOCKER_REGISTRY_SCHEME%/${DOCKER_REGISTRY_SCHEME}/g; \
        s/%DOCKER_REGISTRY_HOST%/${ENV_DOCKER_REGISTRY_HOST}/g; \
        s/%DOCKER_REGISTRY_PORT%/${ENV_DOCKER_REGISTRY_PORT}/g" /etc/nginx/conf.d/default.conf

nginx -g "daemon off;"
